### PR TITLE
Squeekboard upgraded to v1.43.1

### PR DESCRIPTION
**Pull request by svncibrahim**
Squeekboard upgraded to v1.24.0. New patch 0005 added to fix the height issue.

Fixes: #46

### CODE REVIEW

**Comment by Saviq** [comment]
Thanks a lot @svncibrahim! Would you please also submit this to upstream squeekboard here:

https://gitlab.gnome.org/World/Phosh/squeekboard

It would be interesting to know their feedback as well before we commit to maintaining this patch here.

**Comment by svncibrahim** [comment]
"Okay, I will also submit the main squeekboard repository. Thanks!

**Comment by Saviq** [comment]
@svncibrahim hey, can you share the link where you submitted upstream?

**Comment by svncibrahim** [comment]
Hi @Saviq,

I'm sorry for not getting back to you sooner. I didn't send the PR because I needed more time to understand the problem with Squeekboard. While I was looking into it, I found some related issues in the repository. Also, there's a new maintainer of the repository who's making changes. I've been watching the repository closely for a while now. The maintainer has started to make some layout and scaling changes in this [merge request](https://gitlab.gnome.org/World/Phosh/squeekboard/-/merge_requests/639). I just left a comment and added some screenshots about the issue. I'll keep an eye on things and try to help them solve this issue. I guess they didn't notice this issue because they are using higher PPI screen devices like phones and tablets. For now, maybe we could use a patch as a temporary solution. I'll also keep track of the main issue in the repository.

**Comment by Saviq** [comment]
Hi @svncibrahim, do you have any news from upstream?

Comparing `ubuntu-frame-osk --channel 24/stable` (`v1.17`) with `/edge` (`main`) I'm still seeing the same problem :/

**Comment by svncibrahim** [comment]
Hi @Saviq 

Sorry I haven't checked the repo in a while. My issue [#404](https://gitlab.gnome.org/World/Phosh/squeekboard/-/issues/404) got fixed with merge request [#677](https://gitlab.gnome.org/World/Phosh/squeekboard/-/merge_requests/677) you can take a look at the details there. This merge request was released with 1.42.0. In version 1.43.0, they also added some scaling fixes. I tested the latest version, 1.43.1, and everything seems to be working fine now. I’ve attached two screenshots showing the before and after, in 1080p.

v1.24.0
Before

v1.43.1
After

**Comment by Saviq** [comment]
Thanks a bunch @svncibrahim, I've tweaked it to pull from the Ubuntu sources, as we prefer that for security maintenance etc. We'll test it out and merge it if all's good.

**Comment by Saviq** [comment]
@svncibrahim I've also rebased it for `base: core24`, as 22.04 has too old a Meson, and either way we probably don't want to introduce such big a change to the "legacy" `22` track.

Do you need it on `22`? Could you migrate to `24` instead?

**Comment by svncibrahim** [comment]
> Do you need it on `22`? Could you migrate to `24` instead?

Hi @saviq,

I need it on 22 for my project, but it's not a big issue—I can switch to 24 if necessary. By the way, I tested it on 22 and haven't encountered any problems so far.

**Comment by Saviq** [comment]
There is a significant change between how it looks on a 1280x1024 screen:



But on 1920x1080 it looks fine, both horizontal and vertical:





So, good with me!

Thanks again!

**Review by Saviq — APPROVED** [review]

**Pull request merged**
